### ISSUE TITLE
Use systemd to run on boot and restart on failure

### ISSUE THREAD

**Issue by gurchik** [4rm/RUAlertbot#1]
On Raspbian you can save the following in `rualertbot.service` in the repo:

```
[Unit]
Description=RU Alert Bot
After=multi-user.target

[Service]
Type=idle
Restart=always
RestartSec=15
ExecStart=/usr/bin/python3.5 /path/to/RUAlerts.py > /var/log/rualertbot.log 2>&1

[Install]
WantedBy=multi-user.target
```

This will save the script output to `/var/log/rualertbot.log` which needs to be created:

```
$ sudo touch /var/log/rualertbot.log
$ sudo chmod 644 /var/log/rualertbot.log
``` 

To enable, move this file to `/etc/systemd/system` and be sure to change the path above to the actual path to your script, then run:

```
$ sudo systemctl daemon-reload
$ sudo systemctl enable rualertbot.service
$ 
$ # You're done
$ sudo systemctl status rualertbot # to check if it's running
$ sudo systemctl stop rualertbot # to stop it
$ sudo systemctl start rualertbot # to start it
```

**Comment by 4rm** [comment]
Thanks again for this.

> On Raspbian you can save the following in rualertbot.service in the repo:

Sorry, not sure what 'repo' refers to in this context. The directory I currently have RUAlertbot.py saved to?

---

I might implement this in the future, but for now I'm just going to use a loop script. I don't currently see the advantages of systemd.
